CREATE DATABASE IF NOT EXISTS play_card;

USE play_card;

CREATE TABLE IF NOT EXISTS card_variations (
    id SERIAL PRIMARY KEY,
    type VARCHAR(255),
    num int,
    image VARCHAR(255)
);

INSERT INTO card_variations (type, num, image) 
VALUES 
('hearts', 1, 'hearts1.png'),
('hearts', 2, 'hearts2.png'),
('hearts', 3, 'hearts3.png'),
('hearts', 4, 'hearts4.png'),
('hearts', 5, 'hearts5.png'),
('hearts', 6, 'hearts6.png'),
('hearts', 7, 'hearts7.png'),
('hearts', 8, 'hearts8.png'),
('hearts', 9, 'hearts9.png'),
('hearts', 10, 'hearts10.png'),
('hearts', 11, 'hearts11.png'),
('hearts', 12, 'hearts12.png'),
('hearts', 13, 'hearts13.png'),
('diamonds', 1, 'diamonts1.png'),
('diamonds', 2, 'diamonts2.png'),
('diamonds', 3, 'diamonts3.png'),
('diamonds', 4, 'diamonts4.png'),
('diamonds', 5, 'diamonts5.png'),
('diamonds', 6, 'diamonts6.png'),
('diamonds', 7, 'diamonts7.png'),
('diamonds', 8, 'diamonts8.png'),
('diamonds', 9, 'diamonts9.png'),
('diamonds', 10, 'diamonts10.png'),
('diamonds', 11, 'diamonts11.png'),
('diamonds', 12, 'diamonts12.png'),
('diamonds', 13, 'diamonts13.png'),
('clubs', 1, 'clubs1.png'),
('clubs', 2, 'clubs2.png'),
('clubs', 3, 'clubs3.png'),
('clubs', 4, 'clubs4.png'),
('clubs', 5, 'clubs5.png'),
('clubs', 6, 'clubs6.png'),
('clubs', 7, 'clubs7.png'),
('clubs', 8, 'clubs8.png'),
('clubs', 9, 'clubs9.png'),
('clubs', 10, 'clubs10.png'),
('clubs', 11, 'clubs11.png'),
('clubs', 12, 'clubs12.png'),
('clubs', 13, 'clubs13.png'),
('spades', 1, 'spades1.png'),
('spades', 2, 'spades2.png'),
('spades', 3, 'spades3.png'),
('spades', 4, 'spades4.png'),
('spades', 5, 'spades5.png'),
('spades', 6, 'spades6.png'),
('spades', 7, 'spades7.png'),
('spades', 8, 'spades8.png'),
('spades', 9, 'spades9.png'),
('spades', 10, 'spades10.png'),
('spades', 11, 'spades11.png'),
('spades', 12, 'spades12.png'),
('spades', 13, 'spades13.png');